# Generated by Django 5.2.15 on 2026-07-04 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag', '0002_alter_documentchunk_embedding'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='metadata',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
